# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLK2z33sl1_BHZ5gU7DRdJ084f472nMQ
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


df = pd.read_csv('shuffled_tweets_dataset.csv')


nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_tweet(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\@\w+|\#','', text)
    text = re.sub(r'[^\w\s]', '', text)
    tokens = text.split()
    filtered_tokens = [w for w in tokens if w not in stop_words]
    return " ".join(filtered_tokens)


df['cleaned_text'] = df['text'].apply(clean_tweet)


X = df['cleaned_text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

tfidf = TfidfVectorizer(max_features=1000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)


models = {
    "Naïve Bayes": MultinomialNB(),
    "SVM": SVC(kernel='linear'),
    "Logistic Regression": LogisticRegression()
}

results = {}

for name, model in models.items():

    model.fit(X_train_tfidf, y_train)

    predictions = model.predict(X_test_tfidf)

    print(f"\n--- {name} Performance ---")
    print(classification_report(y_test, predictions))
    results[name] = accuracy_score(y_test, predictions)


best_model = max(results, key=results.get)
print(f"\nBest Performing Model: {best_model} with Accuracy: {results[best_model]:.2f}")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. Visualize Model Comparison (Accuracy)
plt.figure(figsize=(10, 6))
sns.barplot(x=list(results.keys()), y=list(results.values()), palette='viridis')
plt.title('Comparison of Classifier Accuracy', fontsize=15)
plt.ylabel('Accuracy Score')
plt.ylim(0, 1.0)
for i, v in enumerate(results.values()):
    plt.text(i, v + 0.02, f"{v:.2f}", ha='center', fontweight='bold')
plt.show()

# 2. Confusion Matrix for the Best Model (e.g., SVM)
# Replace 'svm_model' with the variable name of your best classifier
best_model_obj = models["SVM"]
y_pred = best_model_obj.predict(X_test_tfidf)
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=best_model_obj.classes_,
            yticklabels=best_model_obj.classes_)
plt.title(f'Confusion Matrix: SVM Classifier', fontsize=15)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# 3. Sentiment Distribution Pie Chart
plt.figure(figsize=(8, 8))
df['label'].value_counts().plot.pie(autopct='%1.1f%%', colors=['#66b3ff','#99ff99','#ff9999'], startangle=140)
plt.title('Distribution of Sentiments in Collected Tweets', fontsize=15)
plt.ylabel('') # Hide the y-label
plt.show()